### ISSUE TITLE
regarding the unsupervised method

### ISSUE THREAD

**Issue by seyeeet** [wvangansbeke/Unsupervised-Semantic-Segmentation#10]
Thanks for the great work.
I have a question that appreciate it if you can help me understand it.
For the unsupervised method the DeepUSPS is used if I understand correctly,
can you please clarify if we will retrain it in the code or we just download the pretrained weights for unsupervised DeepUSPS? I was not able to fully grasp that yet :) so if I want to use my custom dataset should I retrain the saliency model?

**Comment by wvangansbeke** [comment]
Hi @seyeeet,
You can use the publicaly available models (see official repos). 
It is actually quite straightforward. You first need to make predictions with DeepUSPS on MSRA (or a similar dataset) with the publicly available code and then train BASNet on the obtained pseudo-labels. We follow this strategy because we noticed that training BASNet with the pseudo-labels from DeepUSPS resulted in masks with higher quality. This bootstrapping procedure is also explained on page 5-6 in section 4.1 of our paper. Now you can make predictions on your target dataset (e.g., PASCAL).
