### ISSUE TITLE
non-object centric dataset

### ISSUE THREAD

**Issue by jancylee** [wvangansbeke/Unsupervised-Semantic-Segmentation#2]
As the paper has mentioned, "Using the object mask proposals, we can assemble a set of object-centric samples even when the dataset itself is non-object centric." I wonder how did you realise it?

**Comment by wvangansbeke** [comment]
Hi @jancylee,

Thank you for your interest.
By using saliency (or any other object prior) you can focus better on the objects in the scene, instead of on the background. By exploiting the saliency masks, we can make sure that the object of interest is present in both augmentations (after resized cropping). Of course saliency also has drawbacks, which are discussed in the paper.

**Comment by jancylee** [comment]
Thanks for your answer. What if the image contains more than one object? like a tabel and a clock in one image at the same time. How the saliency map make sure that only contains one object?

**Comment by wvangansbeke** [comment]
Hi @jancylee,

The primary advantage of the saliency prior is that it allows you to focus on the objects in the scene instead of on the background. If the objects don't overlap, you can extract multiple instance masks with _connected components_. Overlapping objects are still a problem though, but in quite some cases the objects are semantically correlated (e.g. plate on table). We also discuss these limitations, and how to possibly address them, in the paper. Importantly, we show that a (noisy) mid-level prior is significantly better than adopting (less noisy) low-level priors (e.g. edges, super-pixels), since this allows you to learn object information. 

Hope this helps.

**Comment by jancylee** [comment]
Thanks for your prompt reply！
